/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakatjava;

import UAS_alpro.menu_mal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BinatangTernak extends javax.swing.JFrame {

    /**
     * Creates new form BinatangTernak
     */
    public BinatangTernak() {
        initComponents();
    }
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    int sisa;
    PreparedStatement  add = null;

    public void vectortable(int karep, String c, int ekor) {
        int b = karep * ekor;
        Vector v = new Vector();
        v.add(NamaCb.getSelectedItem().toString());
        v.add(karep + c);
        v.add(b);
        DefaultTableModel dt = (DefaultTableModel) TernakTbl.getModel();
        dt.addRow(v);
        JOptionPane.showMessageDialog(this, "Ternak kambing melebihi nishob yaiut 39 maka wajib membayar zakat ternak");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JumlahJiwa = new javax.swing.JTextField();
        HitungFtrh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        NamaCb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TernakTbl = new javax.swing.JTable();
        HitungFtrh1 = new javax.swing.JButton();
        JumlahBin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HitungFtrh2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAKAT BINATANG TERNAK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("HITUNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        JumlahJiwa.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwaMouseClicked(evt);
            }
        });
        getContentPane().add(JumlahJiwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 180, 30));

        HitungFtrh.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh.setText("Bayar");
        HitungFtrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrhMouseClicked(evt);
            }
        });
        HitungFtrh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungFtrhActionPerformed(evt);
            }
        });
        getContentPane().add(HitungFtrh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        NamaCb.setBackground(new java.awt.Color(255, 255, 255));
        NamaCb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        NamaCb.setForeground(new java.awt.Color(0, 0, 0));
        NamaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kambing", "Sapi" }));
        NamaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaCbActionPerformed(evt);
            }
        });
        getContentPane().add(NamaCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 117, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Simpan Zakat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        TernakTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis Binatang", "Zakat Ternak", "Total"
            }
        ));
        TernakTbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TernakTbl.setRowHeight(20);
        TernakTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TernakTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TernakTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 240));

        HitungFtrh1.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh1.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh1.setText("Hitung");
        HitungFtrh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh1MouseClicked(evt);
            }
        });
        HitungFtrh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungFtrh1ActionPerformed(evt);
            }
        });
        getContentPane().add(HitungFtrh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        JumlahBin.setBackground(new java.awt.Color(255, 255, 255));
        JumlahBin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahBin.setForeground(new java.awt.Color(0, 0, 0));
        JumlahBin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JumlahBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahBinMouseClicked(evt);
            }
        });
        JumlahBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBinActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jumlah Binatang Ternak (ekor)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        HitungFtrh2.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh2.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh2.setText("Simpan");
        HitungFtrh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HitungFtrh2MouseEntered(evt);
            }
        });
        HitungFtrh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungFtrh2ActionPerformed(evt);
            }
        });
        getContentPane().add(HitungFtrh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahJiwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwaMouseClicked

    private void HitungFtrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrhMouseClicked
        try {
            // TODO add your handling code here:
            new Order().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BinatangTernak.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_HitungFtrhMouseClicked
    int Uprice = 0;
    private void HitungFtrh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh1MouseClicked
        // TODO add your handling code here:
        if (NamaCb.getSelectedItem().toString().isEmpty() || JumlahBin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Product and Enter Qty");
        } else {
            int tabi = 0;
            int mussinnah = 0;
            String hasil = null;
            int hasil1;
            Uprice = Integer.valueOf(JumlahBin.getText());
            switch (NamaCb.getSelectedIndex()) {
                case 0:
                    String d = " ekor kambing";
                    int harga1 = 2500000;
                    if (Uprice < 40) {
                        JOptionPane.showMessageDialog(this, "Tidak wajib mengeluarkan zakat");
                    } else if (Uprice >= 40 && Uprice < 121) {
                        vectortable(1, d, harga1);
                    } else if (Uprice > 120 && Uprice < 201) {
                        vectortable(2, d, harga1);
                    } else if (Uprice > 200 && Uprice < 301) {
                        vectortable(3, d, harga1);
                    } else {
                        int jumlah = Uprice / 100;
                        vectortable(jumlah, d, harga1);
                    }
                    break;
                case 1:
                    int harga = 2000000;
                    if (Uprice > 30 && Uprice <= 130) {
                        if (Uprice % 30 == 0) {
                            tabi = Uprice / 30;
                        } else {
                            mussinnah = (Uprice - (Uprice % 40)) / 40;
                            tabi = ((Uprice % 40) % 30 == 0) ? (Uprice % 40) / 30 : 0;
                        }
                        mussinnah = mussinnah + 1;
                        hasil = mussinnah + " mussinnah dan " + tabi + " tabi";
                        hasil1 = mussinnah + tabi;
                        vectortable(hasil1, hasil, harga);
                        JOptionPane.showMessageDialog(this, "Ternak Sapi melebihi nishob maka wajib membayar zakat " + hasil);
                    } else if (Uprice > 130) {
                        if (Uprice % 30 == 0) {
                            tabi = Uprice / 30;
                        } else {
                            mussinnah = (Uprice - (Uprice % 40)) / 40;
                            tabi = ((Uprice % 40) % 30 == 0) ? (Uprice % 40) / 30 : 0;
                        }
                        hasil = mussinnah + " mussinnah dan " + tabi + " tabi";
                        hasil1 = mussinnah + tabi;
                        vectortable(hasil1, " ekor sapi", harga);
                        JOptionPane.showMessageDialog(this, "Ternak Sapi melebihi nishob maka wajib membayar zakat " + hasil);
                    } else {
                        JOptionPane.showMessageDialog(this, "Tidak wajib mengeluarkan zakat");
                    }
                    break;
            }
        }
    }//GEN-LAST:event_HitungFtrh1MouseClicked

    private void JumlahBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahBinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahBinMouseClicked

    private void HitungFtrhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungFtrhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrhActionPerformed

    private void HitungFtrh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh2MouseClicked
        // TODO add your handling code here:
        String a = "Zakat Peternakan";
        int i = Integer.valueOf(JumlahJiwa.getText());
        int o = i * 1;
        if (JumlahJiwa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan Nilai");
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/zakat", "root", "");
            add = con.prepareStatement("insert into zakatbl values(?,?)");
            add.setString(1, a);
            add.setInt(2, Integer.valueOf(JumlahJiwa.getText()));
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Zakat Peternakan tersimpan sebesar Rp " + o);
            con.close();
            //SelectProd();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_HitungFtrh2MouseClicked

    private void HitungFtrh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungFtrh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrh2ActionPerformed

    private void HitungFtrh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungFtrh1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_HitungFtrh1ActionPerformed

    private void JumlahBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahBinActionPerformed

    private void NamaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaCbActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new menu_mal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void TernakTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TernakTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TernakTbl.getModel();
        int Myindex = TernakTbl.getSelectedRow();
        JumlahJiwa.setText(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_TernakTblMouseClicked

    private void HitungFtrh2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrh2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BinatangTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BinatangTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BinatangTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BinatangTernak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinatangTernak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungFtrh;
    private javax.swing.JButton HitungFtrh1;
    private javax.swing.JButton HitungFtrh2;
    private javax.swing.JTextField JumlahBin;
    private javax.swing.JTextField JumlahJiwa;
    private javax.swing.JComboBox<String> NamaCb;
    private javax.swing.JTable TernakTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
