/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakatjava;

import UAS_alpro.menu_mal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class EmasPerak extends javax.swing.JFrame {

    /**
     * Creates new form EmasPerak
     */
    public EmasPerak() {
        initComponents();
    }
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    String Zakatname;
    PreparedStatement  add = null;
    int Uprice = 0, Uprice1 = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JumlahJiwa = new javax.swing.JTextField();
        HitungFtrh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Emas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JumlahJiwa1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmasTbl = new javax.swing.JTable();
        HitungFtrh1 = new javax.swing.JButton();
        JumlahJiwa2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HitungFtrh2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAKAT EMAS DAN PERAK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("HITUNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Simpan Zakat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        JumlahJiwa.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwaMouseClicked(evt);
            }
        });
        getContentPane().add(JumlahJiwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        HitungFtrh.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh.setText("Bayar");
        HitungFtrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrhMouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        Emas.setBackground(new java.awt.Color(255, 255, 255));
        Emas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Emas.setForeground(new java.awt.Color(0, 0, 0));
        Emas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emas", "Perak" }));
        getContentPane().add(Emas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 117, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Berat Emas atau Perak (gram)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        JumlahJiwa1.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa1.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa1MouseClicked(evt);
            }
        });
        JumlahJiwa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa1ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 180, 30));

        EmasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Berat", "Harga", "Total"
            }
        ));
        EmasTbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        EmasTbl.setRowHeight(20);
        EmasTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmasTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EmasTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 260));

        HitungFtrh1.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh1.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh1.setText("Hitung");
        HitungFtrh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh1MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        JumlahJiwa2.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa2.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa2MouseClicked(evt);
            }
        });
        JumlahJiwa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa2ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Harga Emas atau Perak / gram");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        HitungFtrh2.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh2.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh2.setText("Simpan");
        HitungFtrh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh2MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahJiwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwaMouseClicked

    private void HitungFtrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrhMouseClicked
        try {
            // TODO add your handling code here:
            new Order().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EmasPerak.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_HitungFtrhMouseClicked

    private void JumlahJiwa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1MouseClicked

    private void JumlahJiwa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1ActionPerformed

    private void HitungFtrh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh1MouseClicked
        // TODO add your handling code here:
        if (Emas.getSelectedItem().toString().isEmpty()||JumlahJiwa.getText().isEmpty()||JumlahJiwa2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select Product and Enter Qty");
        }else{

        switch (Emas.getSelectedIndex()){
            case 0:
                Uprice = Integer.valueOf(JumlahJiwa.getText());
                long a = Uprice*1;
                Uprice1 = Integer.valueOf(JumlahJiwa2.getText());
                long b = Uprice1*1;
                if (a < 78){
                    JOptionPane.showMessageDialog(Emas, "Tidak wajib mengeluarkan zakat");
                }else{
                    long tot = (long) (a * 2.5 / 100);
                    long tot1 = (long) (tot * b);
                    int tot2 = (int) (tot1*1);
                    Vector v = new Vector();
                    v.add(Emas.getSelectedItem().toString());
                    v.add(JumlahJiwa.getText());
                    v.add(JumlahJiwa2.getText());
                    v.add(tot2);
                    DefaultTableModel dt = (DefaultTableModel)EmasTbl.getModel();
                    dt.addRow(v);
                    JOptionPane.showMessageDialog(this, "Karena Nishab Yaitu 78gram Lebih Kecil Dari Emas Anda");
                }
                break;
            case 1:
                Uprice = Integer.valueOf(JumlahJiwa.getText());
                long x = Uprice*1;
                Uprice1 = Integer.valueOf(JumlahJiwa2.getText());
                long y = Uprice1*1;
                if (x < 544){
                    JOptionPane.showMessageDialog(Emas, "Tidak wajib mengeluarkan zakat");
                }else{
                    double tot = (long) (x * 2.5 / 100);
                    long tot1 = (long) (tot * y);
                    Vector v = new Vector();
                    v.add(Emas.getSelectedItem().toString());
                    v.add(JumlahJiwa.getText());
                    v.add(JumlahJiwa2.getText());
                    v.add(tot1);
                    DefaultTableModel dt = (DefaultTableModel)EmasTbl.getModel();
                    dt.addRow(v);
                    JOptionPane.showMessageDialog(this, "Karena Nishab Yaitu 514gram Lebih Kecil Dari Perak Anda");
                }
                break;
            }
        }
    }//GEN-LAST:event_HitungFtrh1MouseClicked

    private void JumlahJiwa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2MouseClicked

    private void JumlahJiwa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2ActionPerformed

    private void HitungFtrh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh2MouseClicked
        // TODO add your handling code here:
        
        String a = "Zakat Emas dan Perak";
        int i = Integer.valueOf(JumlahJiwa1.getText());
        int o = i*1;
        if(JumlahJiwa1.getText().isEmpty()||Emas.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukkan Nilai");
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/zakat","root","");
            add = con.prepareStatement("insert into zakatbl values(?,?)");
            add.setString(1, a);
            add.setInt(2, Integer.valueOf(JumlahJiwa1.getText()));
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Zakat Emas dan Perak tersimpan sebesar Rp " + o);
            con.close();
            //SelectProd();

        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_HitungFtrh2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new menu_mal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void EmasTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmasTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)EmasTbl.getModel();
        int Myindex = EmasTbl.getSelectedRow();
        JumlahJiwa1.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_EmasTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmasPerak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmasPerak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmasPerak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmasPerak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmasPerak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Emas;
    private javax.swing.JTable EmasTbl;
    private javax.swing.JButton HitungFtrh;
    private javax.swing.JButton HitungFtrh1;
    private javax.swing.JButton HitungFtrh2;
    private javax.swing.JTextField JumlahJiwa;
    private javax.swing.JTextField JumlahJiwa1;
    private javax.swing.JTextField JumlahJiwa2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
