/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakatjava;

import GUI.menu_utama;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     * @throws java.sql.SQLException
     */
    public Order() throws SQLException {
        initComponents();
        tampilkanData();
    }
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
public void tampilkanData() throws SQLException{
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/zakat","root","");
        st = (Statement) con.createStatement();
        rs = st.executeQuery("select * from zakatbl");
        //OrderTabel.setModel(DbUtils.resultSetToTableModel(rs));
        int  o = 0;
        while(rs.next()){
                int no = o+1; 
                String nomor = ""+no;
                String jenis = rs.getString(1);
                String nom = rs.getString(2);

                String[] tblData = {nomor,jenis,nom};
                DefaultTableModel model = (DefaultTableModel)OrderTabel.getModel();
                model.addRow(tblData);
            }
        
    }catch(SQLException e){
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalTot = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Hapuslbl = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTabel1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Hapuslbl1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis Zakat", "Nominal Zakat"
            }
        ));
        OrderTabel.setIntercellSpacing(new java.awt.Dimension(0, 0));
        OrderTabel.setRowHeight(20);
        OrderTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrderTabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 289));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOTAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAKAT TAHUNAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Daftar pengeluaran zakat tahunan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        TotalTot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TotalTot.setForeground(new java.awt.Color(0, 0, 0));
        TotalTot.setText("Total");
        getContentPane().add(TotalTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 150, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Simpan");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Rp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, 30));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Hapus");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Cetak");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 80, -1));
        getContentPane().add(Hapuslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, -1));

        OrderTabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Jenis Zakat", "Nominal Zakat"
            }
        ));
        OrderTabel1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        OrderTabel1.setRowHeight(20);
        OrderTabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(OrderTabel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 370, 289));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText(">");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 800, 500));
        getContentPane().add(Hapuslbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int flag = 0,productId,olqty;
    private void OrderTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)OrderTabel.getModel();
        int Myindex = OrderTabel.getSelectedRow();
        Hapuslbl.setText(model.getValueAt(Myindex, 0).toString());
        Hapuslbl1.setText(model.getValueAt(Myindex, 1).toString());
        //HapusTb.setText(model.getValueAt(Myindex,0).toString());
//        productId = Integer.valueOf(model.getValueAt(Myindex,0).toString());
//        olqty = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
//        //ProdDesc.setText(model.getValueAt(Myindex, 3).toString());
//        flag = 1;
    }//GEN-LAST:event_OrderTabelMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try{
            String Id = Hapuslbl1.getText();
            Class.forName("com.mysql.jdbc.Driver");
            con =  DriverManager.getConnection("jdbc:mysql://localhost/zakat","root","");
            String sql ="DELETE FROM `zakatbl` WHERE `zakatbl`.`Jenis` = \'"+Id+"\'";
            st = con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(this, "Data has been deleted");
            tampilkanData();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new menu_utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try{
            OrderTabel.print();
        }catch(Exception exp){
            exp.printStackTrace();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void OrderTabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderTabel1MouseClicked
int i = 1,a,b,total,tot;
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        if (Hapuslbl.getText().isEmpty()||Hapuslbl1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select Zakat ke pembayaran");
        }else{
        a = Integer.valueOf(Hapuslbl1.getText());
        b = a* 1;
        Vector v = new Vector();
        v.add(i);
        v.add(Hapuslbl.getText()); 
        v.add(b);
        DefaultTableModel dt = (DefaultTableModel)OrderTabel1.getModel();
        dt.addRow(v);total = total + tot;
        TotalTot.setText(""+total);
        //update();
        
        //update();
        i++;
        
        }

    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Order().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hapuslbl;
    private javax.swing.JTextField Hapuslbl1;
    private javax.swing.JTable OrderTabel;
    private javax.swing.JTable OrderTabel1;
    private javax.swing.JLabel TotalTot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
