/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakatjava;

import UAS_alpro.menu_mal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Pertanian extends javax.swing.JFrame {

    /**
     * Creates new form Pertanian
     */
    public Pertanian() {
        initComponents();
    }
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    PreparedStatement add = null;

    public void vectorTani(int table3, int table4) {
        Vector v = new Vector();
        v.add(Pengairan.getSelectedItem().toString());
        v.add(KeadaanHasil.getSelectedItem().toString());
        v.add(JumlahJiwa.getText());
        v.add(table3);
        v.add(table4);
        DefaultTableModel dt = (DefaultTableModel) TableTani.getModel();
        dt.addRow(v);
    }

    public void vectorPertanian(int a, int b) {
        int zakatAir;
        int zakatAir1;
        switch (Pengairan.getSelectedIndex()) {
            case 0:
                zakatAir = a * 5 / 100;
                zakatAir1 = zakatAir * b;
                vectorTani(zakatAir, zakatAir1);
                JOptionPane.showMessageDialog(this, "Penghasilan melebihi nishob maka haurs membayar zakat Rp " + zakatAir1);
                break;
            case 1:
                zakatAir = a * 10 / 100;
                zakatAir1 = zakatAir * b;
                vectorTani(zakatAir, zakatAir1);
                JOptionPane.showMessageDialog(this, "Penghasilan melebihi nishob maka haurs membayar zakat Rp " + zakatAir1);
                break;
            case 2:
                zakatAir = a * 75 / 1000;
                zakatAir1 = zakatAir * b;
                vectorTani(zakatAir, zakatAir1);
                JOptionPane.showMessageDialog(this, "Penghasilan melebihi nishob maka haurs membayar zakat Rp " + zakatAir1);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JumlahJiwa = new javax.swing.JTextField();
        HitungFtrh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        KeadaanHasil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JumlahJiwa1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTani = new javax.swing.JTable();
        Pengairan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        HitungFtrh1 = new javax.swing.JButton();
        JumlahJiwa2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HitungFtrh2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAKAT FITRAH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("HITUNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Simpan Zakat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Keadaan Hasil Tani");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        JumlahJiwa.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwaMouseClicked(evt);
            }
        });
        getContentPane().add(JumlahJiwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 30));

        HitungFtrh.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh.setText("Simpan");
        HitungFtrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrhMouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        KeadaanHasil.setBackground(new java.awt.Color(255, 255, 255));
        KeadaanHasil.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        KeadaanHasil.setForeground(new java.awt.Color(0, 0, 0));
        KeadaanHasil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah dibersihkan dari jerami atau kulitnya", "Belum dibersihkan dari jerami atau kulitnya" }));
        KeadaanHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeadaanHasilActionPerformed(evt);
            }
        });
        getContentPane().add(KeadaanHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hasil Tani (Kilogram)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        JumlahJiwa1.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa1.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa1MouseClicked(evt);
            }
        });
        JumlahJiwa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa1ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 180, 30));

        TableTani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pengairan", "Keadaan", "Hasil", "Zakat", "Total"
            }
        ));
        TableTani.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableTani.setRowHeight(20);
        TableTani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableTani);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 470, 270));

        Pengairan.setBackground(new java.awt.Color(255, 255, 255));
        Pengairan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Pengairan.setForeground(new java.awt.Color(0, 0, 0));
        Pengairan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air Irigasi", "Air Hujan atau Air Sungai", "Air Irigasi dan Air Hujan atau Air Sungai" }));
        getContentPane().add(Pengairan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 117, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cara Pengairan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        HitungFtrh1.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh1.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh1.setText("Hitung");
        HitungFtrh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh1MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        JumlahJiwa2.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa2.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JumlahJiwa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa2MouseClicked(evt);
            }
        });
        JumlahJiwa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa2ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Harga Barang Tani / Kilogram");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        HitungFtrh2.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh2.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh2.setText("Bayar");
        HitungFtrh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh2MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahJiwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwaMouseClicked

    private void HitungFtrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrhMouseClicked
        // TODO add your handling code here:

        String a = "Zakat Pertanian";
        int i = Integer.valueOf(JumlahJiwa1.getText());
        int o = i * 1;
        if (JumlahJiwa1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan Nilai");
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/zakat", "root", "");
            add = con.prepareStatement("insert into zakatbl values(?,?)");
            add.setString(1, a);
            add.setInt(2, Integer.valueOf(JumlahJiwa1.getText()));
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Zakat Pertanian tersimpan sebesar Rp " + o);
            con.close();
            //SelectProd();

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_HitungFtrhMouseClicked

    private void JumlahJiwa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1MouseClicked

    private void JumlahJiwa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1ActionPerformed

    private void HitungFtrh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh1MouseClicked
        // TODO add your handling code here:

        if (Pengairan.getSelectedItem().toString().isEmpty() || JumlahJiwa.getText().isEmpty() || KeadaanHasil.getSelectedItem().toString().isEmpty() || JumlahJiwa2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Product and Enter Qty");
        } else {
            int hasilTani = Integer.valueOf(JumlahJiwa.getText());
            int hargaTani = Integer.valueOf(JumlahJiwa2.getText());
            switch (KeadaanHasil.getSelectedIndex()) {
                case 0:
                    if (hasilTani < 653) {
                        JOptionPane.showMessageDialog(this, "Tidak wajib membayar zakat, Karena nisab zakat pertanian adalah 5 wasaq = 653 kg beras.");
                    } else {
                        vectorPertanian(hasilTani, hargaTani);
                    }
                    break;
                case 1:
                    if (hasilTani < 1000) {
                        JOptionPane.showMessageDialog(this, "Tidak wajib membayar zakat, karena berat nishob 1 ton");
                    } else {
                        vectorPertanian(hasilTani, hargaTani);
                    }
                    break;
            }
        }

    }//GEN-LAST:event_HitungFtrh1MouseClicked

    private void JumlahJiwa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2MouseClicked

    private void JumlahJiwa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2ActionPerformed

    private void HitungFtrh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh2MouseClicked
        try {
            // TODO add your handling code here:
            new Order().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pertanian.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_HitungFtrh2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new menu_mal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void KeadaanHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeadaanHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeadaanHasilActionPerformed

    private void TableTaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTaniMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableTani.getModel();
        int Myindex = TableTani.getSelectedRow();
        JumlahJiwa1.setText(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_TableTaniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertanian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertanian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertanian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertanian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertanian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungFtrh;
    private javax.swing.JButton HitungFtrh1;
    private javax.swing.JButton HitungFtrh2;
    private javax.swing.JTextField JumlahJiwa;
    private javax.swing.JTextField JumlahJiwa1;
    private javax.swing.JTextField JumlahJiwa2;
    private javax.swing.JComboBox<String> KeadaanHasil;
    private javax.swing.JComboBox<String> Pengairan;
    private javax.swing.JTable TableTani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
