/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakatjava;

/**
 *
 * @author DELL
 */
public class TambangdanTemuan extends javax.swing.JFrame {

    /**
     * Creates new form TambangdanTemuan
     */
    public TambangdanTemuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JumlahJiwa = new javax.swing.JTextField();
        HitungFtrh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        NamaCb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JumlahJiwa1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JenisCb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        HitungFtrh1 = new javax.swing.JButton();
        JumlahJiwa2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HitungFtrh2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAKAT BARANG TAMBANG DAN TEMUAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("HITUNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Simpan Zakat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        JumlahJiwa.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JumlahJiwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwaMouseClicked(evt);
            }
        });
        JumlahJiwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwaActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 30));

        HitungFtrh.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh.setText("Bayar");
        HitungFtrh.setToolTipText("");
        HitungFtrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrhMouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.setToolTipText("");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        NamaCb.setBackground(new java.awt.Color(255, 255, 255));
        NamaCb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        NamaCb.setForeground(new java.awt.Color(0, 0, 0));
        NamaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NamaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaCbActionPerformed(evt);
            }
        });
        getContentPane().add(NamaCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 117, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Berat Emas atau Perak (Gram)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        JumlahJiwa1.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa1.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JumlahJiwa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa1MouseClicked(evt);
            }
        });
        JumlahJiwa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa1ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 180, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis", "Nama", "Berat", "Harga", "Total"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 500, 270));

        JenisCb.setBackground(new java.awt.Color(255, 255, 255));
        JenisCb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JenisCb.setForeground(new java.awt.Color(0, 0, 0));
        JenisCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(JenisCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 117, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jenis Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        HitungFtrh1.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh1.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh1.setText("Hitung");
        HitungFtrh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh1MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        JumlahJiwa2.setBackground(new java.awt.Color(255, 255, 255));
        JumlahJiwa2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JumlahJiwa2.setForeground(new java.awt.Color(0, 0, 0));
        JumlahJiwa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JumlahJiwa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JumlahJiwa2MouseClicked(evt);
            }
        });
        JumlahJiwa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahJiwa2ActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahJiwa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Harga Emas atau Perak");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        HitungFtrh2.setBackground(new java.awt.Color(204, 255, 204));
        HitungFtrh2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HitungFtrh2.setForeground(new java.awt.Color(0, 0, 0));
        HitungFtrh2.setText("Simpan");
        HitungFtrh2.setToolTipText("");
        HitungFtrh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungFtrh2MouseClicked(evt);
            }
        });
        getContentPane().add(HitungFtrh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahJiwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwaMouseClicked

    private void HitungFtrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrhMouseClicked

    private void NamaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaCbActionPerformed

    private void JumlahJiwa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1MouseClicked

    private void JumlahJiwa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa1ActionPerformed

    private void JumlahJiwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwaActionPerformed

    private void HitungFtrh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrh1MouseClicked

    private void JumlahJiwa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JumlahJiwa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2MouseClicked

    private void JumlahJiwa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahJiwa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahJiwa2ActionPerformed

    private void HitungFtrh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungFtrh2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungFtrh2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambangdanTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambangdanTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambangdanTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambangdanTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambangdanTemuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungFtrh;
    private javax.swing.JButton HitungFtrh1;
    private javax.swing.JButton HitungFtrh2;
    private javax.swing.JComboBox<String> JenisCb;
    private javax.swing.JTextField JumlahJiwa;
    private javax.swing.JTextField JumlahJiwa1;
    private javax.swing.JTextField JumlahJiwa2;
    private javax.swing.JComboBox<String> NamaCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
