/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_alpro;

import GUI.menu_utama;
import zakatjava.BarangDagang;
import zakatjava.BinatangTernak;
import zakatjava.EmasPerak;
import zakatjava.Pertanian;

/**
 *
 * @author alikh
 */
public class menu_mal extends javax.swing.JFrame {

    /**
     * Creates new form menu_mal
     */
    public menu_mal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        perdagangan = new javax.swing.JLabel();
        emas = new javax.swing.JLabel();
        kembali2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pertanian = new javax.swing.JLabel();
        ternak = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Zakat Perdagangan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Zakat Emas/Perak");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 60, -1, 20));

        perdagangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/perdagangan-removebg-preview.png"))); // NOI18N
        perdagangan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perdaganganAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        perdagangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perdaganganMouseClicked(evt);
            }
        });
        jPanel1.add(perdagangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, 130));

        emas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/emas-removebg-preview.png"))); // NOI18N
        emas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                emasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        emas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emasMouseClicked(evt);
            }
        });
        jPanel1.add(emas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 170, 130));

        kembali2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/back-removebg-preview.png"))); // NOI18N
        kembali2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembali2MouseClicked(evt);
            }
        });
        jPanel1.add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 70, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Zakat Pertanian");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Zakat Hewan Ternak");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 280, -1, -1));

        pertanian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/pertanian-removebg-preview.png"))); // NOI18N
        pertanian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pertanianMouseClicked(evt);
            }
        });
        jPanel1.add(pertanian, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 170, 130));

        ternak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/hewan_ternak-removebg-preview.png"))); // NOI18N
        ternak.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ternakAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ternak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ternakMouseClicked(evt);
            }
        });
        jPanel1.add(ternak, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 170, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS_alpro/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembali2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali2MouseClicked
        // TODO add your handling code here:
        new menu_utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembali2MouseClicked

    private void perdaganganAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perdaganganAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_perdaganganAncestorAdded

    private void emasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_emasAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emasAncestorAdded

    private void pertanianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pertanianMouseClicked
        // TODO add your handling code here:
         new Pertanian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pertanianMouseClicked

    private void ternakAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ternakAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ternakAncestorAdded

    private void perdaganganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perdaganganMouseClicked
        // TODO add your handling code here:
        new BarangDagang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perdaganganMouseClicked

    private void emasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emasMouseClicked
        // TODO add your handling code here:
        new EmasPerak().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_emasMouseClicked

    private void ternakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ternakMouseClicked
        // TODO add your handling code here:
        new BinatangTernak().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ternakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_mal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_mal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kembali2;
    private javax.swing.JLabel perdagangan;
    private javax.swing.JLabel pertanian;
    private javax.swing.JLabel ternak;
    // End of variables declaration//GEN-END:variables
}
